### ISSUE TITLE
Add omniauth-twitter2 to the list of community maintained strategies

### ISSUE THREAD

**Issue by babilonczyk** [unasuke/omniauth-twitter2#1]
https://github.com/omniauth/omniauth/wiki/List-of-Strategies

**Comment by unasuke** [comment]
@babilonczyk Thank you for your proposal. I'll add later.

**Comment by unasuke** [comment]
I added. Thanks.

![image](https://user-images.githubusercontent.com/4487291/183363661-f6bd539d-d6be-46c4-ba53-7fd9e99429b7.png)
